### ISSUE TITLE
Keras 2.02 ImportError: cannot import name 'get_from_module'

### ISSUE THREAD

**Issue by isaacmg** [maxpumperla/elephas#48]
I'm trying to use elephas with Keras 2.02 (model is only compatible with the new version). and get the following error: ImportError: cannot import name 'get_from_module'. This is likely due to there being no get_from_module in Keras 2.02. Is there a quick fix that anyone is aware of to get it working with 2.02?

**Comment by rubenohayon** [comment]
Yes I have the same error

**Comment by feay1234** [comment]
I got the same error when I use Keras 2, the problem has been solved by using Keras 1.

I believe get_from_module has been removed from Keras 2

**Comment by NicGian** [comment]
I too have the same error when calling "from elephas import optimizers"

**Comment by maxpumperla** [comment]
this should be resolved by #50 above. Install from master, please. Will need more time for another release.

**Comment by NarjesKar** [comment]
Go to elephas.optimizers and change the line 'from keras.utils.generic_utils import get_from_module' to 'from thinc.extra._vendorized.keras_generic_utils import get_from_module'
