### ISSUE TITLE
Elephas slice_X error

### ISSUE THREAD

**Issue by ducminhnguyen** [maxpumperla/elephas#18]
Elephas encounter this error with the latest theano. Can you help me fix this.
```
Traceback (most recent call last):
  File "/home/zeus/workspace/./KerasOnSparkElephas.py", line 28, in <module>
    from elephas.spark_model import SparkModel
  File "/home/zeus/anaconda2/lib/python2.7/site-packages/elephas/spark_model.py", line 18, in <module>
    from keras.models import model_from_yaml, slice_X
ImportError: cannot import name slice_X

**Comment by maxpumperla** [comment]
Sure, the problem seems to be that in the new Keras version ```slice_X``` is gone from ```keras.models```, theano is fine. I'll have to update elephas to run on keras 1.0. I can probably start tomorrow, not sure.

For now, if you have an urgent use case, consider pinning an older keras version in your virtualenv or something along the line.

**Comment by ducminhnguyen** [comment]
I change the import for slice_X then this error comes up, is this a keras version error.
```
File "/home/zeus/spark-1.6.1/python/lib/pyspark.zip/pyspark/worker.py", line 111, in main
    process()
  File "/home/zeus/spark-1.6.1/python/lib/pyspark.zip/pyspark/worker.py", line 106, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/zeus/spark-1.6.1/python/lib/pyspark.zip/pyspark/serializers.py", line 263, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/home/zeus/anaconda2/lib/python2.7/site-packages/elephas/spark_model.py", line 266, in train
    model.fit(x_train, y_train, show_accuracy=True, **self.train_config)
  File "/home/zeus/anaconda2/lib/python2.7/site-packages/keras/models.py", line 388, in fit
    return self.model.fit(x, y,
AttributeError: 'NoneType' object has no attribute 'fit'

**Comment by maxpumperla** [comment]
This error indicates that ```model``` is not a proper keras model, as expected, but rather has type ```None```, i.e. the deserialization might have gone wrong. Hence there's no ```fit``` method available.

What exactly do you mean by "change the import for slice_X"?

**Comment by ducminhnguyen** [comment]
I mean I found slice_X new path in keras and change the import to the new path.

The model compiled so I guess it should work I will include the code.

```
from __future__ import absolute_import
from __future__ import print_function

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras.utils import np_utils

from elephas.spark_model import SparkModel
from elephas.utils.rdd_utils import to_simple_rdd
from elephas import optimizers as elephas_optimizers

from pyspark import SparkContext, SparkConf

# Define basic parameters
batch_size = 64
nb_classes = 10
nb_epoch = 3

# Create Spark context
conf = SparkConf().setAppName('Mnist_Spark_MLP').setMaster('local[8]')
sc = SparkContext(conf=conf)

# Load data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype("float32")
x_test = x_test.astype("float32")
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# Convert class vectors to binary class matrices
y_train = np_utils.to_categorical(y_train, nb_classes)
y_test = np_utils.to_categorical(y_test, nb_classes)

model = Sequential()
model.add(Dense(128, input_dim=784))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(10))
model.add(Activation('softmax'))

# Compile model
sgd = SGD(lr=0.1)
model.compile(loss='categorical_crossentropy', optimizer=sgd)
# Build RDD from numpy features and labels
rdd = to_simple_rdd(sc, x_train, y_train)

# Initialize SparkModel from Keras model and Spark context
print(model.to_yaml())
adagrad = elephas_optimizers.Adagrad()
spark_model = SparkModel(sc,
                         model,
                         optimizer=adagrad,
                         frequency='epoch',
                         mode='asynchronous',
                         num_workers=2)

# Train Spark model
spark_model.train(rdd, nb_epoch=nb_epoch, batch_size=batch_size, verbose=2, validation_split=0.1)

# Evaluate Spark model by evaluating the underlying model
score = spark_model.master_network.evaluate(x_test, y_test, show_accuracy=True, verbose=2)

**Comment by ducminhnguyen** [comment]
If I run the model without elephas and spark it works fine.

**Comment by ducminhnguyen** [comment]
Ok I found an error in spark_model, you load the yaml but you have not compile the model so it returns an error, add a line to compile models solve my problem.

**Comment by maxpumperla** [comment]
That's cool, thanks for putting in the effort. Would you want to create a pull request for this?

**Comment by ducminhnguyen** [comment]
Ok I will modify some detail then submit a pull request

**Comment by maxpumperla** [comment]
Thanks, really appreciated!

**Comment by newzhx** [comment]
I meet this problem, too, how do you solve it?

**Comment by maxpumperla** [comment]
See #22, I still have to migrate to Keras 1.0. Please work with Keras 0.3 for now if you want to use elephas. Thanks!

**Comment by newzhx** [comment]
Thank for your work.

**Comment by haoyangz** [comment]
As discussed in #22 , master branch now supports keras 1.x . To install this part of (un-released) updates, re-install elephas by  
```
pip install --upgrade --no-deps git+git://github.com/maxpumperla/elephas
```

**Comment by maxpumperla** [comment]
@haoyangz thanks for helping out here. Bit busy at the moment, but I'm preparing a new release to finally remedy this.

**Comment by MeethuM** [comment]
I am getting the error ImportError: cannot import name slice_X with the elephas version 0.3 and keras 1.1.1.
I could see the change in the path of import statement in elephas master branch but not in 0.3 which is version we get via pip install

**Comment by helderm** [comment]
I tried running elephas by installing it thorugh pip and still got this error. Can't this issue be opened again until a realase where this bug is fixed is deployed to Pypi?

**Comment by marty90** [comment]
I solved by installing it with
`pip3 install git+https://github.com/maxpumperla/elephas`

**Comment by ivan-bilan** [comment]
Does Elephas support Keras 2? I am getting this error on 2.1.

**Comment by ivanmontero** [comment]
https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L358

It seems like the `slice_X` method in Keras has been renamed `_slice_arrays`.

**Comment by maxpumperla** [comment]
I closed it because it has been addressed a while ago. It's on master, just not on pypi

**Comment by MihailoBackovic** [comment]
I tried pip3 install git+https://github.com/maxpumperla/elephas  but getting an error: 

ImportError: cannot import name 'slice_arrays'.

Using keras 2.0.5.

Any ideas how to resolve this?

**Comment by maxpumperla** [comment]
@mm1mm you need to update keras. this is a little annoying, but keras has first renamed `slice_X` to `slice_arrays`, but then also moved it several times without backward compatibility. Check out [requirements](https://github.com/maxpumperla/elephas/blob/master/requirements.txt) for recommended versions.

**Comment by maxpumperla** [comment]
p.s. please open a new ticket next time. it's difficult to track stuff that's been closed for ages. thanks :+1:
